export const ShopItemsActionTypes = {
    UPDATE_ITEMS_LIST: 'UPDATE_ITEMS_LIST',

    FETCH_ITEMS_START: 'FETCH_ITEMS_START',
    FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
    FETCH_ITEMS_FAILURE: 'FETCH_ITEMS_FAILURE',

    FETCH_SHOP_START: 'FETCH_SHOP_START',
    FETCH_SHOP_SUCCESS: 'FETCH_SHOP_SUCCESS',
    FETCH_SHOP_FAILURE: 'FETCH_SHOP_FAILURE',

    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',

    UPDATE_ITEMS_BY_REQUEST_FROM_SEARCH_FORM: 'UPDATE_ITEMS_BY_REQUEST_FROM_SEARCH_FORM',
    UPDATE_ITEMS_FROM_CATEGORY: 'UPDATE_ITEMS_FROM_CATEGORY',
    UPDATE_CATEGORIES: 'UPDATE_CATEGORIES',
    DISPLAY_ALL_ITEMS: 'DISPLAY_ALL_ITEMS',
    DISPLAY_LIMITED_ITEMS: 'DISPLAY_LIMITED_ITEMS',
    DISPLAY_ITEMS_FROM_CATEGORY: 'DISPLAY_ITEMS_FROM_CATEGORY',
    DISPLAY_ITEMS_BY_REQUEST_FROM_SEARCH_FORM: 'DISPLAY_ITEMS_BY_REQUEST_FROM_SEARCH_FORM',
    DISPLAY_ABOUT: 'DISPLAY_ABOUT'
};
