export const ShopItemsActionTypes = {
    UPDATE_ITEMS_LIST: 'UPDATE_ITEMS_LIST',
    UPDATE_ITEMS_BY_REQUEST_FROM_SEARCH_FORM: 'UPDATE_ITEMS_BY_REQUEST_FROM_SEARCH_FORM',
    UPDATE_ITEMS_FROM_CATEGORY: 'UPDATE_ITEMS_FROM_CATEGORY',
    UPDATE_CATEGORIES: 'UPDATE_CATEGORIES',
    DISPLAY_ALL_ITEMS: 'DISPLAY_ALL_ITEMS',
    DISPLAY_LIMITED_ITEMS: 'DISPLAY_LIMITED_ITEMS',
    DISPLAY_ITEMS_FROM_CATEGORY: 'DISPLAY_ITEMS_FROM_CATEGORY',
    DISPLAY_ITEMS_BY_REQUEST_FROM_SEARCH_FORM: 'DISPLAY_ITEMS_BY_REQUEST_FROM_SEARCH_FORM',
    DISPLAY_ABOUT: 'DISPLAY_ABOUT'
};
